version: "3"
services:
  reply-concept-users:
    container_name: users-app
    build: ./users-app/.
    image: users-app
    restart: on-failure
    volumes:
      - ./users-app/app:/usr/src/app
    ports:
      - "15000:3000" 
    command: npm run dev  
  reply-concept-cars:
    container_name: cars-app
    build: ./cars-app/.
    image: cars-app
    restart: on-failure
    volumes:
      - ./cars-app/app:/usr/src/app
    ports:
      - "15001:3000"       
    command: npm run dev
  reply-concept-demands:
    container_name: demands-app
    build: ./demands-app/.
    image: demands-app
    restart: on-failure
    volumes:
      - ./demands-app/app:/usr/src/app
    ports:
      - "15002:3000"       
    command: npm run dev
  reply-concept-simulator:
    container_name: simulator-app
    build: ./simulator-app/.
    image: simulator-app
    restart: on-failure
    depends_on: 
      - reply-concept-cars
    volumes:
      - ./simulator-app/app:/usr/src/app     
    command: ["/wait-for-it.sh", "cars-app:3000", "--", "npm", "run", "start"]