version: "3"
services:
  reply-concept-users:
    container_name: users-app
    build: ./users-app/.
    image: users-app
    restart: on-failure
    volumes:
      - ./users-app/app:/usr/src/app
    ports:
      - "15000:3000" 
  reply-concept-cars:
    container_name: cars-app
    build: ./cars-app/.
    image: cars-app
    restart: on-failure
    volumes:
      - ./cars-app/app:/usr/src/app
    ports:
      - "15001:3000"       
    command: npm run dev